/*
 * sound-balance-electron
 * Copyright (C) 2026 Pavel Alloyarov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
import type {
	AUDIO_ENCODERS,
	AUDIO_FILTERS,
	AUDIO_MUXER_EXTENSIONS,
	EXTENSIONS,
} from "./settings.types";

export const CONCURRENCY_OPTIONS = Array.from({ length: 10 }, (_, i) => ({
	value: String(i + 1),
}));

export const FILTER_OPTIONS = {
	acompressor: {
		name: "acompressor",
		desc: "A compressor is mainly used to reduce the dynamic range of a signal.",
		options: [
			{
				type: "number",
				label: "level_in",
				desc: "Set input gain. Range is between 0.015625 and 64.",
				defaultValue: 1,
				min: 0.015625,
				max: 64,
			},
			{
				type: "select",
				label: "mode",
				desc: "Set mode of compressor operation.",
				options: ["downward", "upward"],
				defaultValue: "downward",
			},
			{
				type: "number",
				label: "threshold",
				desc: "Set a threshold above which a stream signal affects gain reduction. Range is between 0.00097563 and 1.",
				defaultValue: 0.125,
				min: 0.00097563,
				max: 1,
			},
			{
				type: "number",
				label: "ratio",
				desc: "Set a ratio by which the signal is reduced. Range is between 1 and 20.",
				defaultValue: 2,
				min: 1,
				max: 20,
			},
			{
				type: "number",
				label: "attack",
				desc: "Amount of milliseconds the signal has to rise above the threshold before gain reduction starts. Range is between 0.01 and 2000.",
				defaultValue: 20,
				min: 0.01,
				max: 2000,
			},
			{
				type: "number",
				label: "release",
				desc: "Amount of milliseconds the signal has to fall below the threshold before reduction is decreased again. Range is between 0.01 and 9000.",
				defaultValue: 250,
				min: 0.01,
				max: 9000,
			},
			{
				type: "number",
				label: "makeup",
				desc: "Set the amount by how much signal will be amplified after processing. Range is between 1 and 64.",
				defaultValue: 1,
				min: 1,
				max: 64,
			},
			{
				type: "number",
				label: "knee",
				desc: "Curve the sharp knee around the threshold to enter gain reduction more softly. Range is between 1 and 8.",
				defaultValue: 2.82843,
				min: 1,
				max: 8,
			},
			{
				type: "select",
				label: "link",
				desc: "Choose if the average level between all channels of input stream or the louder(maximum) channel of input stream affects the reduction.",
				options: ["average", "maximum"],
				defaultValue: "average",
			},
			{
				type: "select",
				label: "detection",
				desc: "Should the exact signal be taken in case of peak or an RMS one in case of rms.",
				options: ["peak", "rms"],
				defaultValue: "rms",
			},
			{
				type: "number",
				label: "mix",
				desc: "How much to use compressed signal in output. Range is between 0 and 1.",
				defaultValue: 1,
				min: 0,
				max: 1,
			},
		],
	},
	acontrast: {
		name: "acontrast",
		desc: "Simple audio dynamic range compression/expansion filter.",
		options: [
			{
				type: "number",
				label: "mix",
				desc: "Set contrast. Range is between 0 and 100.",
				defaultValue: 33,
				min: 0,
				max: 100,
			},
		],
	},
	acrusher: {
		name: "acrusher",
		desc: "Reduce audio bit resolution.",
		options: [
			{
				type: "number",
				label: "level_in",
				desc: "Set level in. Pre-crush input gain. Range is between 0.015625 and 64.",
				defaultValue: 1,
				min: 0.015625,
				max: 64,
			},
			{
				type: "number",
				label: "level_out",
				desc: "Set level out. Post-crush output gain. Range is between 0.015625 and 64.",
				defaultValue: 1,
				min: 0.015625,
				max: 64,
			},
			{
				type: "number",
				label: "bit",
				desc: "Set bit reduction. Target simulated bit depth. Range is between 1 and 32.",
				defaultValue: 8,
				min: 1,
				max: 32,
			},
			{
				type: "number",
				label: "mix",
				desc: "Set mixing amount. 0 = unprocessed input, 1 = fully crushed output. Range is between 0 and 1.",
				defaultValue: 0.5,
				min: 0,
				max: 1,
			},
			{
				type: "select",
				label: "mode",
				desc: "Quantization curve selector.",
				options: ["lin", "log"],
				defaultValue: "lin",
			},
			{
				type: "number",
				label: "dc",
				desc: "Set DC offset applied before quantization. Range is between -1 and 1.",
				defaultValue: 1,
				min: 0.25,
				max: 4,
			},
			{
				type: "number",
				label: "aa",
				desc: "Set anti-aliasing blend factor. Range is between 0 and 1.",
				defaultValue: 0.5,
				min: 0,
				max: 1,
			},
			{
				type: "number",
				label: "samples",
				desc: "Set sample rate reduction factor. Range is between 1 and 250.",
				defaultValue: 1,
				min: 1,
				max: 250,
			},
			{
				type: "switch",
				label: "lfo",
				desc: "Enable LFO (Low-Frequency Oscillator).",
				defaultValue: false,
			},
			{
				type: "number",
				label: "lforange",
				desc: "Set LFO modulation depth range. Range is between 1 and 250.",
				defaultValue: 20,
				min: 1,
				max: 250,
			},
			{
				type: "number",
				label: "lforate",
				desc: "Set LFO rate. Range is between 0.01 and 200.",
				defaultValue: 0.3,
				min: 1,
				max: 200,
			},
		],
	},
	adeclick: {
		name: "adeclick",
		desc: "Remove impulsive noise from input audio.",
		options: [
			{
				type: "number",
				label: "window",
				desc: "Set window size, in milliseconds. This sets size of window which will be processed at once. Range is between 10 and 100.",
				defaultValue: 55,
				min: 10,
				max: 100,
			},
			{
				type: "number",
				label: "overlap",
				desc: "Set window overlap, in percentage of window size. Setting this to a very high value increases impulsive noise removal but makes whole process much slower. Range is between 50 and 95.",
				defaultValue: 75,
				min: 50,
				max: 95,
			},
			{
				type: "number",
				label: "arorder",
				desc: "Set autoregression order, in percentage of window size. This option also controls quality of interpolated samples using neighbour good samples. Range is between 0 and 25.",
				defaultValue: 2,
				min: 0,
				max: 25,
			},
			{
				type: "number",
				label: "treshold",
				desc: "Set threshold value. This controls the strength of impulsive noise which is going to be removed. The lower value, the more samples will be detected as impulsive noise. Range is between 1 and 100.",
				defaultValue: 2,
				min: 1,
				max: 100,
			},
			{
				type: "number",
				label: "burst",
				desc: "Set burst fusion, in percentage of window size. If any two samples detected as noise are spaced less than this value then any sample between those two samples will be also detected as noise. Range is between 0 and 10.",
				defaultValue: 2,
				min: 0,
				max: 10,
			},
			{
				type: "select",
				label: "method",
				desc: "Set overlap method.",
				options: ["add", "save"],
				defaultValue: "add",
			},
		],
	},
	adeclip: {
		name: "adeclip",
		desc: "Remove clipping from input audio.",
		options: [
			{
				type: "number",
				label: "window",
				desc: "Set window size, in milliseconds. This sets size of window which will be processed at once. Range is between 10 and 100.",
				defaultValue: 55,
				min: 10,
				max: 100,
			},
			{
				type: "number",
				label: "overlap",
				desc: "Set window overlap, in percentage of window size. Range is between 50 and 95.",
				defaultValue: 75,
				min: 50,
				max: 95,
			},
			{
				type: "number",
				label: "arorder",
				desc: "Set autoregression order, in percentage of window size. This option also controls quality of interpolated samples using neighbour good samples. Range is between 0 and 25.",
				defaultValue: 8,
				min: 0,
				max: 25,
			},
			{
				type: "number",
				label: "treshold",
				desc: "Set threshold value. Higher values make clip detection less aggressive. Range is between 1 and 100.",
				defaultValue: 10,
				min: 1,
				max: 100,
			},
			{
				type: "number",
				label: "hsize",
				desc: "Set size of histogram used to detect clips. Higher values make clip detection less aggressive. Range is between 100 and 9999.",
				defaultValue: 1000,
				min: 100,
				max: 9999,
			},
			{
				type: "select",
				label: "method",
				desc: "Set overlap method.",
				options: ["add", "save"],
				defaultValue: "add",
			},
		],
	},
	adecorrelate: {
		name: "adecorrelate",
		desc: "Apply decorrelation to input audio.",
		options: [
			{
				type: "number",
				label: "stages",
				desc: "Set decorrelation stages of filtering. Range is between 1 and 16.",
				defaultValue: 6,
				min: 1,
				max: 16,
			},
			{
				type: "number",
				label: "seed",
				desc: "Set random seed used for setting delay in samples across channels.",
				defaultValue: -1,
				min: -1,
				max: Number.MAX_SAFE_INTEGER,
			},
		],
	},
	adelay: {
		name: "adelay",
		desc: "Delay one or more audio channels.",
		options: [
			{
				type: "text",
				label: "delays",
				desc: "Set list of delays in milliseconds for each channel separated by '|'. Unused delays will be silently ignored. If number of given delays is smaller than number of channels all remaining channels will not be delayed. If you want to delay exact number of samples, append 'S' to number. If you want instead to delay in seconds, append 's' to number.",
				defaultValue: "",
			},
			{
				type: "switch",
				label: "all",
				desc: "Use last set delay for all remaining channels.",
				defaultValue: false,
			},
		],
	},
	adenorm: {
		name: "adenorm",
		desc: "Remedy denormals by adding extremely low-level noise.",
		options: [
			{
				type: "number",
				label: "level",
				desc: "Set level of added noise in dB. Range is between 1 and 16.",
				defaultValue: -351,
				min: 1,
				max: 16,
			},
			{
				type: "select",
				label: "type",
				desc: "Set type of added noise.",
				options: [
					{ label: "dc - add DC signal", value: "dc" },
					{ label: "ac - add AC signal", value: "ac" },
					{ label: "square - add square signal", value: "square" },
					{ label: "pulse - add pulse signal", value: "pulse" },
				],
				defaultValue: "dc",
			},
		],
	},
	adrc: {
		name: "adrc",
		desc: "Audio Spectral Dynamic Range Controller.",
		options: [
			{
				type: "select",
				label: "transfer",
				desc: "Set the transfer expression.",
				options: [
					{ label: "ch - current channel number", value: "ch" },
					{ label: "sn - current sample number", value: "sn" },
					{ label: "nb_channels -number of channels", value: "nb_channels" },
					{ label: "t - timestamp expressed in seconds", value: "t" },
					{ label: "sr - sample rate", value: "sr" },
					{ label: "p - current frequency power value, in dB", value: "p" },
					{ label: "f - current frequency in Hz", value: "f" },
				],
				defaultValue: "p",
			},
		],
	},
	adynamicequalizer: {
		name: "adynamicequalizer",
		desc: "Apply Dynamic Equalization of input audio.",
		options: [
			{
				type: "number",
				label: "threshold",
				desc: "Set the detection threshold used to trigger equalization. Threshold detection is using detection filter. Range is between 0 and 100.",
				defaultValue: 0,
				min: 0,
				max: 100,
			},
			{
				type: "number",
				label: "dfrequency",
				desc: "Set the detection frequency in Hz used for detection filter used to trigger equalization. Range is between 2 and 1000000 Hz.",
				defaultValue: 1000,
				min: 2,
				max: 1000000,
			},
			{
				type: "number",
				label: "dqfactor",
				desc: "Set the detection resonance factor for detection filter used to trigger equalization. Range is between 0.001 and 1000.",
				defaultValue: 1,
				min: 0.001,
				max: 1000,
			},
			{
				type: "number",
				label: "tfrequency",
				desc: "Set the target frequency of equalization filter. Range is between 2 and 1000000 Hz.",
				defaultValue: 1000,
				min: 2,
				max: 1000000,
			},
			{
				type: "number",
				label: "tqfactor",
				desc: "Set the target resonance factor for target equalization filter. Range is between 0.001 and 1000.",
				defaultValue: 1,
				min: 0.001,
				max: 1000,
			},
			{
				type: "number",
				label: "attack",
				desc: "Set the amount of milliseconds the signal from detection has to rise above the detection threshold before equalization starts. Range is between 1 and 2000.",
				defaultValue: 20,
				min: 1,
				max: 2000,
			},
			{
				type: "number",
				label: "release",
				desc: "Set the amount of milliseconds the signal from detection has to fall below the detection threshold before equalization ends. Range is between 1 and 2000.",
				defaultValue: 200,
				min: 1,
				max: 2000,
			},
			{
				type: "number",
				label: "ratio",
				desc: "Set the ratio by which the equalization gain is raised. Range is between 0 and 30.",
				defaultValue: 1,
				min: 0,
				max: 30,
			},
			{
				type: "number",
				label: "makeup",
				desc: "Set the makeup offset by which the equalization gain is raised. Range is between 0 and 100.",
				defaultValue: 0,
				min: 0,
				max: 100,
			},
			{
				type: "number",
				label: "range",
				desc: "Set the max allowed cut/boost amount. Range is between 1 and 200.",
				defaultValue: 50,
				min: 1,
				max: 200,
			},
			{
				type: "select",
				label: "mode",
				desc: "Set the mode of filter operation.",
				options: [
					{
						label: "listen - output only isolated detection signal.",
						value: "listen",
					},
					{
						label: "cutbelow - cut frequencies below detection threshold.",
						value: "cutbelow",
					},
					{
						label: "cutabove - cut frequencies above detection threshold.",
						value: "cutabove",
					},
					{
						label: "boostbelow - boost frequencies below detection threshold.",
						value: "boostbelow",
					},
					{
						label: "boostabove - boost frequencies above detection threshold.",
						value: "boostabove",
					},
				],
				defaultValue: "cutbelow",
			},
			{
				type: "select",
				label: "tftype",
				desc: "Set the type of target filter.",
				options: ["bell", "lowshelf", "highshelf"],
				defaultValue: "bell",
			},
			{
				type: "select",
				label: "auto",
				desc: "Automatically gather threshold from detection filter. This option is useful to detect threshold in certain time frame of input audio stream, in such case option value is changed at runtime.",
				options: [
					{
						label:
							"disabled - disable using automatically gathered threshold value.",
						value: "disabled",
					},
					{
						label: "off - stop picking threshold value.",
						value: "off",
					},
					{
						label: "on - start picking threshold value.",
						value: "on",
					},
					{
						label:
							"adaptive - adaptively pick threshold value, by calculating sliding window entropy.",
						value: "adaptive",
					},
				],
				defaultValue: "disabled",
			},
			{
				type: "select",
				label: "precision",
				desc: "Set which precision to use when processing samples.",
				options: ["auto", "float", "double"],
				defaultValue: "auto",
			},
		],
	},
	adynamicsmooth: {
		name: "adynamicsmooth",
		desc: "Apply Dynamic Smoothing to input audio stream.",
		options: [
			{
				type: "number",
				label: "sensitivity",
				desc: "Set an amount of sensitivity to frequency fluctations. Range is between 0 and 1e+06.",
				defaultValue: 2,
				min: 0,
				max: 1e6,
			},
			{
				type: "number",
				label: "basefreq",
				desc: "Set a base frequency for smoothing. Range is between 2 and 1e+06.",
				defaultValue: 22050,
				min: 2,
				max: 1e6,
			},
		],
	},
	aecho: {
		name: "aecho",
		desc: "Add echoing to the audio input.",
		options: [
			{
				type: "number",
				label: "in_gain",
				desc: "Set input gain of reflected signal. Range is between 0 and 1.",
				defaultValue: 0.6,
				min: 0,
				max: 1,
			},
			{
				type: "number",
				label: "out_gain",
				desc: "Set output gain of reflected signal. Range is between 0 and 1.",
				defaultValue: 0.3,
				min: 0,
				max: 1,
			},
			{
				type: "text",
				label: "delays",
				desc: "Set list of time intervals in milliseconds between original signal and reflections separated by '|'. Range of each delay is between 0 and 9000.0.",
				defaultValue: "1000",
			},
			{
				type: "text",
				label: "decays",
				desc: "Set list of loudness of reflected signals separated by '|'. Range of each decay is between 0 and 1.0.",
				defaultValue: "0.5",
			},
		],
	},
	aemphasis: {
		name: "aemphasis",
		desc: "Audio emphasis.",
		options: [
			{
				type: "number",
				label: "level_in",
				desc: "Set input gain. Range is between 0 and 64.",
				defaultValue: 1,
				min: 0,
				max: 64,
			},
			{
				type: "number",
				label: "level_out",
				desc: "Set output gain. Range is between 0 and 64.",
				defaultValue: 1,
				min: 0,
				max: 64,
			},
			{
				type: "select",
				label: "mode",
				desc: "Set filter mode. For restoring material use reproduction mode, otherwise use production mode.",
				options: ["reproduction", "production"],
				defaultValue: "reproduction",
			},
			{
				type: "select",
				label: "type",
				desc: "Set filter type.",
				options: [
					{
						label: "col - select Columbia.",
						value: "col",
					},
					{
						label: "emi - select EMI.",
						value: "emi",
					},
					{
						label: "bsi - select BSI (78RPM).",
						value: "bsi",
					},
					{
						label: "riaa - select RIAA.",
						value: "riaa",
					},
					{
						label: "cd - select Compact Disc (CD).",
						value: "cd",
					},
					{
						label: "50fm - select 50\u00B5 (FM).",
						value: "50fm",
					},
					{
						label: "75fm - select 75\u00B5 (FM).",
						value: "75fm",
					},
					{
						label: "50kf - select 50\u00B5 (FM-KF).",
						value: "50kf",
					},
					{
						label: "75kf - select 75\u00B5 (FM-KF).",
						value: "75kf",
					},
				],
				defaultValue: "cd",
			},
		],
	},
	aeval: {
		name: "aeval",
		desc: "Filter audio signal according to a specified expression. This filter accepts one or more expressions (one for each channel), which are evaluated and used to modify a corresponding audio signal.",
		options: [
			{
				type: "text",
				label: "exprs",
				desc: "Set the '|'-separated expressions list for each separate channel. If the number of input channels is greater than the number of expressions, the last specified expression is used for the remaining output channels.",
				defaultValue: "",
			},
			{
				type: "text",
				label: "channel_layout",
				desc: "Set output channel layout. If not specified, the channel layout is specified by the number of expressions. If set to 'same', it will use by default the same input channel layout.",
				defaultValue: "",
			},
		],
	},
	aexciter: {
		name: "aexciter",
		desc: "An exciter is used to produce high sound that is not present in the original signal. This is done by creating harmonic distortions of the signal which are restricted in range and added to the original signal. An Exciter raises the upper end of an audio signal without simply raising the higher frequencies.",
		options: [
			{
				type: "number",
				label: "level_in",
				desc: "Set input level prior processing of signal. Range is between 0 and 64.",
				defaultValue: 1,
				min: 0,
				max: 64,
			},
			{
				type: "number",
				label: "level_out",
				desc: "Set output level after processing of signal. Range is between 0 and 64.",
				defaultValue: 1,
				min: 0,
				max: 64,
			},
			{
				type: "number",
				label: "amount",
				desc: "Set the amount of harmonics added to original signal. Range is between 0 and 64.",
				defaultValue: 1,
				min: 0,
				max: 64,
			},
			{
				type: "number",
				label: "drive",
				desc: "Set the amount of newly created harmonics. Range is between 0.1 and 10.",
				defaultValue: 8.5,
				min: 0.1,
				max: 10,
			},
			{
				type: "number",
				label: "blend",
				desc: "Set the octave of newly created harmonics. Range is between -10 and 10.",
				defaultValue: 0,
				min: -10,
				max: 10,
			},
			{
				type: "number",
				label: "freq",
				desc: "Set the lower frequency limit of producing harmonics in Hz. Range is between 2000 and 12000 Hz.",
				defaultValue: 7500,
				min: 2000,
				max: 12000,
			},
			{
				type: "number",
				label: "ceil",
				desc: "Set the upper frequency limit of producing harmonics. Range is between 9999 and 20000 Hz.",
				defaultValue: 9999,
				min: 9999,
				max: 20000,
			},
			{
				type: "switch",
				label: "listen",
				desc: "Mute the original signal and output only added harmonics.",
				defaultValue: false,
			},
		],
	},
	afade: {
		name: "afade",
		desc: "Fade in/out input audio.",
		options: [
			{
				type: "select",
				label: "type",
				desc: "Specify the effect type.",
				options: ["in", "out"],
				defaultValue: "in",
			},
			{
				type: "number",
				label: "start_sample",
				desc: "Specify the number of the start sample for starting to apply the fade effect.",
				defaultValue: 0,
				min: 0,
				max: Number.MAX_SAFE_INTEGER,
			},
			{
				type: "number",
				label: "nb_samples",
				desc: "Specify the number of samples for which the fade effect has to last.",
				defaultValue: 44100,
				min: 1,
				max: Number.MAX_SAFE_INTEGER,
			},
			{
				type: "number",
				label: "start_time",
				desc: "Specify the start time of the fade effect.",
				defaultValue: 0,
				min: 0,
				max: Number.MAX_SAFE_INTEGER,
			},
			{
				type: "number",
				label: "duration",
				desc: "Specify the duration of the fade effect.",
				defaultValue: 0,
				min: 0,
				max: Number.MAX_SAFE_INTEGER,
			},
			{
				type: "select",
				label: "type",
				desc: "Specify the effect type.",
				options: [
					{
						label: "tri - select triangular, linear slope",
						value: "tri",
					},
					{
						label: "qsin - select quarter of sine wave",
						value: "qsin",
					},
					{
						label: "hsin - select half of sine wave",
						value: "hsin",
					},
					{
						label: "esin - select exponential sine wave",
						value: "esin",
					},
					{
						label: "log - select logarithmic",
						value: "log",
					},
					{
						label: "ipar - select inverted parabola",
						value: "ipar",
					},
					{
						label: "qua - select quadratic",
						value: "qua",
					},
					{
						label: "cub - select cubic",
						value: "cub",
					},
					{
						label: "squ - select square root",
						value: "squ",
					},
					{
						label: "cbr - select cubic root",
						value: "cbr",
					},
					{
						label: "par - select parabola",
						value: "par",
					},
					{
						label: "exp - select exponential",
						value: "exp",
					},
					{
						label: "iqsin - select inverted quarter of sine wave",
						value: "iqsin",
					},
					{
						label: "ihsin - select inverted half of sine wave",
						value: "ihsin",
					},
					{
						label: "dese - select double-exponential seat",
						value: "dese",
					},
					{
						label: "desi - select double-exponential sigmoid",
						value: "desi",
					},
					{
						label: "losi - select logistic sigmoid",
						value: "losi",
					},
					{
						label: "sinc - select sine cardinal function",
						value: "sinc",
					},
					{
						label: "isinc - select inverted sine cardinal function",
						value: "isinc",
					},
					{
						label: "quat - select quartic",
						value: "quat",
					},
					{
						label: "quatr - select quartic root",
						value: "quatr",
					},
					{
						label: "qsin2 - select squared quarter of sine wave",
						value: "qsin2",
					},
					{
						label: "hsin2 - select squared half of sine wave",
						value: "hsin2",
					},
					{
						label: "nofade - no fade applied",
						value: "nofade",
					},
				],
				defaultValue: "tri",
			},
			{
				type: "number",
				label: "silence",
				desc: "Set the initial gain for fade-in or final gain for fade-out. Range is between 0 and 1.",
				defaultValue: 0,
				min: 0,
				max: 1,
			},
			{
				type: "number",
				label: "unity",
				desc: "Set the initial gain for fade-out or final gain for fade-in. Range is between 0 and 1.",
				defaultValue: 1,
				min: 0,
				max: 1,
			},
		],
	},
	dynaudnorm: {
		name: "dynaudnorm",
		desc: "Dynamic Audio Normalizer. This filter applies a certain amount of gain to the input audio in order to bring its peak magnitude to a target level.",
		options: [
			{
				type: "number",
				label: "framlen",
				desc: "Set the frame length in milliseconds. Range is between 10 and 8000 milliseconds.",
				defaultValue: 500,
				min: 10,
				max: 8000,
			},
			{
				type: "number",
				label: "gausssize",
				desc: "Set the Gaussian filter window size. Range is between 3 and 301. Must be odd number.",
				defaultValue: 31,
				min: 3,
				max: 301,
			},
			{
				type: "number",
				label: "peak",
				desc: "Set the target peak value. This specifies the highest permissible magnitude level for the normalized audio input. Range is between 0 and 1.",
				defaultValue: 0.95,
				min: 0,
				max: 1,
			},
			{
				type: "number",
				label: "maxgain",
				desc: "Set the maximum gain factor. Range is between 1 and 100.",
				defaultValue: 10,
				min: 0,
				max: 100,
			},
			{
				type: "number",
				label: "targetrms",
				desc: "Set the target RMS. Range is between 0 and 1.",
				defaultValue: 0,
				min: 0,
				max: 1,
			},
			{
				type: "number",
				label: "targetrms",
				desc: "Set the target RMS. Range is between 0 and 1.",
				defaultValue: 0,
				min: 0,
				max: 1,
			},
			{
				type: "switch",
				label: "coupling",
				desc: "Enable channels coupling.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "correctdc",
				desc: "Enable DC bias correction.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "altboundary",
				desc: "Enable alternative boundary mode.",
				defaultValue: false,
			},
			{
				type: "number",
				label: "compress",
				desc: "Set the compress factor. Range is between 0 and 30.",
				defaultValue: 0,
				min: 0,
				max: 30,
			},
			{
				type: "number",
				label: "treshold",
				desc: "Set the compress factor. Range is between 0 and 1.",
				defaultValue: 0,
				min: 0,
				max: 1,
			},
			{
				type: "text",
				label: "channels",
				desc: "Specify which channels to filter.",
				defaultValue: "all",
			},
			{
				type: "number",
				label: "overlap",
				desc: "Specify overlap for frames. Range is between 0 and 1.",
				defaultValue: 0,
				min: 0,
				max: 1,
			},
			{
				type: "text",
				label: "curve",
				desc: "Specify the peak mapping curve expression which is going to be used when calculating gain applied to frames.",
				defaultValue: "",
			},
		],
	},
	loudnorm: {
		name: "loudnorm",
		desc: "EBU R128 loudness normalization. Includes both dynamic and linear normalization modes.",
		options: [
			{
				type: "number",
				label: "I",
				desc: "Set integrated loudness target. Range is between -70 and -5.",
				defaultValue: -24,
				min: -70,
				max: -5,
			},
			{
				type: "number",
				label: "LRA",
				desc: "Set loudness range target. Range is between 1 and 50.",
				defaultValue: 7,
				min: 1,
				max: 50,
			},
			{
				type: "number",
				label: "TP",
				desc: "Set maximum true peak. Range is between -9 and 0.",
				defaultValue: -2,
				min: -9,
				max: 0,
			},
			{
				type: "number",
				label: "offset",
				desc: "Set offset gain. Range is between -99 and 99.",
				defaultValue: 0,
				min: -99,
				max: 99,
			},
			{
				type: "switch",
				label: "linear",
				desc: "Normalize by linearly scaling the source audio.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "dual_mono",
				desc: "Treat mono input files as dual-mono.",
				defaultValue: true,
			},
			{
				type: "select",
				label: "print_format",
				desc: "Set print format for stats.",
				options: ["none", "summary", "json"],
				defaultValue: "none",
			},
			{
				type: "text",
				label: "stats_file",
				desc: "Write stats to specified file.",
				defaultValue: "",
			},
		],
	},
	// afftdn: {
	// 	name: "afftdn",
	// 	desc: "Denoise audio samples using FFT.",
	// 	options: [],
	// },
	// afftfilt: {
	// 	name: "afftfilt",
	// 	desc: "Apply arbitrary expressions to samples in frequency domain.",
	// 	options: [],
	// },
	// aformat: {
	// 	name: "aformat",
	// 	desc: "Convert the input audio to one of the specified formats.",
	// 	options: [],
	// },
	// afreqshift: {
	// 	name: "afreqshift",
	// 	desc: "Apply frequency shifting to input audio.",
	// 	options: [],
	// },
	// afwtdn: {
	// 	name: "afwtdn",
	// 	desc: "Denoise audio stream using Wavelets.",
	// 	options: [],
	// },
	// agate: { name: "agate", desc: "Audio gate.", options: [] },
	// aintegral: {
	// 	name: "aintegral",
	// 	desc: "Compute integral of input audio.",
	// 	options: [],
	// },
	// alatency: {
	// 	name: "alatency",
	// 	desc: "Report audio filtering latency.",
	// 	options: [],
	// },
	// alimiter: { name: "alimiter", desc: "Audio lookahead limiter.", options: [] },
	// allpass: {
	// 	name: "allpass",
	// 	desc: "Apply a two-pole all-pass filter.",
	// 	options: [],
	// },
	// aloop: { name: "aloop", desc: "Loop audio samples.", options: [] },
	// ametadata: {
	// 	name: "ametadata",
	// 	desc: "Manipulate audio frame metadata.",
	// 	options: [],
	// },
	// amultiply: {
	// 	name: "amultiply",
	// 	desc: "Multiply two audio streams.",
	// 	options: [],
	// },
	// anlmdn: {
	// 	name: "anlmdn",
	// 	desc: "Reduce broadband noise from stream using Non-Local Means.",
	// 	options: [],
	// },
	// anlmf: {
	// 	name: "anlmf",
	// 	desc: "Apply Normalized Least-Mean-Fourth algorithm to first audio stream.",
	// 	options: [],
	// },
	// anlms: {
	// 	name: "anlms",
	// 	desc: "Apply Normalized Least-Mean-Squares algorithm to first audio stream.",
	// 	options: [],
	// },
	// anull: {
	// 	name: "anull",
	// 	desc: "Pass the source unchanged to the output.",
	// 	options: [],
	// },
	// apad: { name: "apad", desc: "Pad audio with silence.", options: [] },
	// aperms: {
	// 	name: "aperms",
	// 	desc: "Set permissions for the output audio frame.",
	// 	options: [],
	// },
	// aphaser: {
	// 	name: "aphaser",
	// 	desc: "Add a phasing effect to the audio.",
	// 	options: [],
	// },
	// aphaseshift: {
	// 	name: "aphaseshift",
	// 	desc: "Apply phase shifting to input audio.",
	// 	options: [],
	// },
	// apsnr: {
	// 	name: "apsnr",
	// 	desc: "Measure Audio Peak Signal-to-Noise Ratio.",
	// 	options: [],
	// },
	// apsyclip: {
	// 	name: "apsyclip",
	// 	desc: "Audio Psychoacoustic Clipper.",
	// 	options: [],
	// },
	// apulsator: { name: "apulsator", desc: "Audio pulsator.", options: [] },
	// arealtime: {
	// 	name: "arealtime",
	// 	desc: "Slow down filtering to match realtime.",
	// 	options: [],
	// },
	// aresample: { name: "aresample", desc: "Resample audio data.", options: [] },
	// areverse: { name: "areverse", desc: "Reverse an audio clip.", options: [] },
	// arls: {
	// 	name: "arls",
	// 	desc: "Apply Recursive Least Squares algorithm to first audio stream.",
	// 	options: [],
	// },
	// arnndn: {
	// 	name: "arnndn",
	// 	desc: "Reduce noise from speech using Recurrent Neural Networks.",
	// 	options: [],
	// },
	// asdr: {
	// 	name: "asdr",
	// 	desc: "Measure Audio Signal-to-Distortion Ratio.",
	// 	options: [],
	// },
	// asendcmd: {
	// 	name: "asendcmd",
	// 	desc: "Send commands to filters.",
	// 	options: [],
	// },
	// asetnsamples: {
	// 	name: "asetnsamples",
	// 	desc: "Set the number of samples for each output audio frames.",
	// 	options: [],
	// },
	// asetpts: {
	// 	name: "asetpts",
	// 	desc: "Set PTS for the output audio frame.",
	// 	options: [],
	// },
	// asetrate: {
	// 	name: "asetrate",
	// 	desc: "Change the sample rate without altering the data.",
	// 	options: [],
	// },
	// asettb: {
	// 	name: "asettb",
	// 	desc: "Set timebase for the audio output link.",
	// 	options: [],
	// },
	// ashowinfo: {
	// 	name: "ashowinfo",
	// 	desc: "Show textual information for each audio frame.",
	// 	options: [],
	// },
	// asidedata: {
	// 	name: "asidedata",
	// 	desc: "Manipulate audio frame side data.",
	// 	options: [],
	// },
	// asisdr: {
	// 	name: "asisdr",
	// 	desc: "Measure Audio Scale-Invariant Signal-to-Distortion Ratio.",
	// 	options: [],
	// },
	// asoftclip: { name: "asoftclip", desc: "Audio Soft Clipper.", options: [] },
	// aspectralstats: {
	// 	name: "aspectralstats",
	// 	desc: "Show frequency domain statistics about audio frames.",
	// 	options: [],
	// },
	// asr: { name: "asr", desc: "Automatic Speech Recognition.", options: [] },
	// astats: {
	// 	name: "astats",
	// 	desc: "Show time domain statistics about audio frames.",
	// 	options: [],
	// },
	// asubboost: {
	// 	name: "asubboost",
	// 	desc: "Boost subwoofer frequencies.",
	// 	options: [],
	// },
	// asubcut: { name: "asubcut", desc: "Cut subwoofer frequencies.", options: [] },
	// asupercut: { name: "asupercut", desc: "Cut super frequencies.", options: [] },
	// asuperpass: {
	// 	name: "asuperpass",
	// 	desc: "Apply high order Butterworth band-pass filter.",
	// 	options: [],
	// },
	// asuperstop: {
	// 	name: "asuperstop",
	// 	desc: "Apply high order Butterworth band-stop filter.",
	// 	options: [],
	// },
	// atempo: { name: "atempo", desc: "Adjust audio tempo.", options: [] },
	// atilt: { name: "atilt", desc: "Apply spectral tilt to audio.", options: [] },
	// atrim: {
	// 	name: "atrim",
	// 	desc: "Pick one continuous section from the input, drop the rest.",
	// 	options: [],
	// },
	// axcorrelate: {
	// 	name: "axcorrelate",
	// 	desc: "Cross-correlate two audio streams.",
	// 	options: [],
	// },
	// azmq: {
	// 	name: "azmq",
	// 	desc: "Receive commands through ZMQ and broker them to filters.",
	// 	options: [],
	// },
	// bandpass: {
	// 	name: "bandpass",
	// 	desc: "Apply a two-pole Butterworth band-pass filter.",
	// 	options: [],
	// },
	// bandreject: {
	// 	name: "bandreject",
	// 	desc: "Apply a two-pole Butterworth band-reject filter.",
	// 	options: [],
	// },
	// bass: { name: "bass", desc: "Boost or cut lower frequencies.", options: [] },
	// biquad: {
	// 	name: "biquad",
	// 	desc: "Apply a biquad IIR filter with the given coefficients.",
	// 	options: [],
	// },
	// bs2b: { name: "bs2b", desc: "Bauer stereo-to-binaural filter.", options: [] },
	// channelmap: {
	// 	name: "channelmap",
	// 	desc: "Remap audio channels.",
	// 	options: [],
	// },
	// chorus: {
	// 	name: "chorus",
	// 	desc: "Add a chorus effect to the audio.",
	// 	options: [],
	// },
	// compand: {
	// 	name: "compand",
	// 	desc: "Compress or expand audio dynamic range.",
	// 	options: [],
	// },
	// compensationdelay: {
	// 	name: "compensationdelay",
	// 	desc: "Audio Compensation Delay Line.",
	// 	options: [],
	// },
	// crossfeed: {
	// 	name: "crossfeed",
	// 	desc: "Apply headphone crossfeed filter.",
	// 	options: [],
	// },
	// crystalizer: {
	// 	name: "crystalizer",
	// 	desc: "Simple audio noise sharpening filter.",
	// 	options: [],
	// },
	// dcshift: {
	// 	name: "dcshift",
	// 	desc: "Apply a DC shift to the audio.",
	// 	options: [],
	// },
	// deesser: {
	// 	name: "deesser",
	// 	desc: "Apply de-essing to the audio.",
	// 	options: [],
	// },
	// dialoguenhance: {
	// 	name: "dialoguenhance",
	// 	desc: "Audio Dialogue Enhancement.",
	// 	options: [],
	// },
	// drmeter: {
	// 	name: "drmeter",
	// 	desc: "Measure audio dynamic range.",
	// 	options: [],
	// },
	// earwax: { name: "earwax", desc: "Widen the stereo image.", options: [] },
	// equalizer: {
	// 	name: "equalizer",
	// 	desc: "Apply two-pole peaking equalization (EQ) filter.",
	// 	options: [],
	// },
	// extrastereo: {
	// 	name: "extrastereo",
	// 	desc: "Increase difference between stereo audio channels.",
	// 	options: [],
	// },
	// firequalizer: {
	// 	name: "firequalizer",
	// 	desc: "Finite Impulse Response Equalizer.",
	// 	options: [],
	// },
	// flanger: {
	// 	name: "flanger",
	// 	desc: "Apply a flanging effect to the audio.",
	// 	options: [],
	// },
	// haas: { name: "haas", desc: "Apply Haas Stereo Enhancer.", options: [] },
	// hdcd: {
	// 	name: "hdcd",
	// 	desc: "Apply High Definition Compatible Digital (HDCD) decoding.",
	// 	options: [],
	// },
	// highpass: {
	// 	name: "highpass",
	// 	desc: "Apply a high-pass filter with 3dB point frequency.",
	// 	options: [],
	// },
	// highshelf: {
	// 	name: "highshelf",
	// 	desc: "Apply a high shelf filter.",
	// 	options: [],
	// },
	// lowpass: {
	// 	name: "lowpass",
	// 	desc: "Apply a low-pass filter with 3dB point frequency.",
	// 	options: [],
	// },
	// lowshelf: {
	// 	name: "lowshelf",
	// 	desc: "Apply a low shelf filter.",
	// 	options: [],
	// },
	// mcompand: {
	// 	name: "mcompand",
	// 	desc: "Multiband Compress or expand audio dynamic range.",
	// 	options: [],
	// },
	// pan: {
	// 	name: "pan",
	// 	desc: "Remix channels with coefficients (panning).",
	// 	options: [],
	// },
	// replaygain: { name: "replaygain", desc: "ReplayGain scanner.", options: [] },
	// rubberband: {
	// 	name: "rubberband",
	// 	desc: "Apply time-stretching and pitch-shifting.",
	// 	options: [],
	// },
	// sidechaincompress: {
	// 	name: "sidechaincompress",
	// 	desc: "Sidechain compressor.",
	// 	options: [],
	// },
	// sidechaingate: {
	// 	name: "sidechaingate",
	// 	desc: "Audio sidechain gate.",
	// 	options: [],
	// },
	// silencedetect: {
	// 	name: "silencedetect",
	// 	desc: "Detect silence.",
	// 	options: [],
	// },
	// silenceremove: {
	// 	name: "silenceremove",
	// 	desc: "Remove silence.",
	// 	options: [],
	// },
	// sofalizer: {
	// 	name: "sofalizer",
	// 	desc: "SOFAlizer (Spatially Oriented Format for Acoustics).",
	// 	options: [],
	// },
	// speechnorm: { name: "speechnorm", desc: "Speech Normalizer.", options: [] },
	// stereotools: {
	// 	name: "stereotools",
	// 	desc: "Apply various stereo tools.",
	// 	options: [],
	// },
	// stereowiden: {
	// 	name: "stereowiden",
	// 	desc: "Apply stereo widening effect.",
	// 	options: [],
	// },
	// superequalizer: {
	// 	name: "superequalizer",
	// 	desc: "Apply 18 band equalization filter.",
	// 	options: [],
	// },
	// surround: {
	// 	name: "surround",
	// 	desc: "Apply audio surround upmix filter.",
	// 	options: [],
	// },
	// tiltshelf: {
	// 	name: "tiltshelf",
	// 	desc: "Apply a tilt shelf filter.",
	// 	options: [],
	// },
	// treble: {
	// 	name: "treble",
	// 	desc: "Boost or cut upper frequencies.",
	// 	options: [],
	// },
	// tremolo: { name: "tremolo", desc: "Apply tremolo effect.", options: [] },
	// vibrato: { name: "vibrato", desc: "Apply vibrato effect.", options: [] },
	// virtualbass: {
	// 	name: "virtualbass",
	// 	desc: "Audio Virtual Bass.",
	// 	options: [],
	// },
	// volume: { name: "volume", desc: "Change input volume.", options: [] },
	// volumedetect: {
	// 	name: "volumedetect",
	// 	desc: "Detect audio volume.",
	// 	options: [],
	// },
	// afifo: {
	// 	name: "afifo",
	// 	desc: "Buffer input frames and send them when they are requested.",
	// 	options: [],
	// },
} satisfies Partial<AUDIO_FILTERS>;

export const ENCODER_OPTIONS = {
	aac: {
		name: "aac",
		desc: "Advanced Audio Coding (AAC) encoder. This encoder is the default AAC encoder, natively implemented into FFmpeg.",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Set bit rate in bits/s. Setting this automatically activates constant bit rate (CBR) mode.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
			{
				type: "number",
				label: "cutoff",
				desc: "Set cutoff frequency. If unspecified (0), the encoder dynamically adjusts the cutoff to improve clarity on low bitrates.",
				defaultValue: 0,
				min: 0,
				max: 24000,
			},
			{
				type: "select",
				label: "aac_coder",
				desc: "Set AAC encoder coding method.",
				defaultValue: "twoloop",
				options: [
					{
						label: "twoloop - Two loop searching (TLS) method (default)",
						value: "twoloop",
					},
					{
						label:
							"anmr - Average noise to mask ratio (ANMR) trellis-based solution (experimental, not recommended)",
						value: "anmr",
					},
					{
						label: "fast - Constant quantizer method (better at high bitrates)",
						value: "fast",
					},
				],
			},
			{
				type: "select",
				label: "aac_ms",
				desc: "Sets mid/side coding mode.",
				defaultValue: "auto",
				options: ["auto", "enable", "disable"],
			},
			{
				type: "switch",
				label: "aac_is",
				desc: "Sets intensity stereo coding tool usage.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "aac_pns",
				desc: "Uses perceptual noise substitution.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "aac_tns",
				desc: "Enables the use of a multitap FIR filter to hide quantization noise.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "aac_ltp",
				desc: "Enables long term prediction extension for very low bandwidth situations (e.g., voice or solo piano).",
				defaultValue: false,
			},
			{
				type: "select",
				label: "profile",
				desc: "Sets the encoding profile.",
				defaultValue: "aac_low",
				options: [
					{
						label: "aac_low - AAC Low-complexity profile (most compatible)",
						value: "aac_low",
					},
					{
						label: "mpeg2_aac_low - MPEG-2 AAC Low-complexity (disables PNS)",
						value: "mpeg2_aac_low",
					},
					{
						label: "aac_ltp - Long term prediction profile (enables aac_ltp)",
						value: "aac_ltp",
					},
				],
			},
		],
	},
	ac3: {
		name: "ac3",
		desc: "AC-3 audio encoder using floating-point math. Implements ATSC A/52:2010 and ETSI TS 102 366.",
		category: "Lossy General Audio",
		options: [
			{
				type: "switch",
				label: "per_frame_metadata",
				desc: "Allow per-frame metadata changes. If disabled, metadata values set at initialization are used for every frame.",
				defaultValue: false,
			},
			{
				type: "select",
				label: "center_mixlev",
				desc: "Center Mix Level. The amount of gain applied to center channel when downmixing to stereo.",
				defaultValue: "0.595",
				options: [
					{ label: "0.707 - Apply -3dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6dB gain", value: "0.500" },
				],
			},
			{
				type: "select",
				label: "surround_mixlev",
				desc: "Surround Mix Level. The amount of gain applied to surround channel(s) when downmixing to stereo.",
				defaultValue: "0.500",
				options: [
					{ label: "0.707 - Apply -3dB gain", value: "0.707" },
					{ label: "0.500 - Apply -6dB gain", value: "0.500" },
					{ label: "0.000 - Silence surround channel(s)", value: "0.000" },
				],
			},
			{
				type: "number",
				label: "mixing_level",
				desc: "Mixing Level - peak SPL in production environment (80 to 111). Valid values are 80 to 111. Use -1 for unknown. If room_type is not default, this must not be -1.",
				defaultValue: -1,
				min: -1,
				max: 111,
			},
			{
				type: "select",
				label: "room_type",
				desc: "Room Type - describes equalization used during final mixing.",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{
						label: "large - Large Room (dubbing stage with X-curve)",
						value: "large",
					},
					{ label: "small - Small Room (flat equalization)", value: "small" },
				],
			},
			{
				type: "switch",
				label: "copyright",
				desc: "Copyright Indicator - specifies whether a copyright exists for this audio.",
				defaultValue: false,
			},
			{
				type: "number",
				label: "dialnorm",
				desc: "Dialogue Normalization - how far average dialogue level is below 0 dBFS. Default -31 means no volume change.",
				defaultValue: -31,
				min: -31,
				max: -1,
			},
			{
				type: "select",
				label: "dsur_mode",
				desc: "Dolby Surround Mode - indicates if stereo signal uses Dolby Surround (Pro Logic). Does NOT actually apply Dolby Surround processing.",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "off - Not Dolby Surround Encoded", value: "off" },
					{ label: "on - Dolby Surround Encoded", value: "on" },
				],
			},
			{
				type: "switch",
				label: "original",
				desc: "Original Bit Stream Indicator - specifies whether audio is from original source and not a copy.",
				defaultValue: true,
			},
			{
				type: "select",
				label: "dmix_mode",
				desc: "Preferred Stereo Downmix Mode - selects Lt/Rt (Dolby Surround) or Lo/Ro (normal stereo).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "ltrt - Lt/Rt Downmix Preferred", value: "ltrt" },
					{ label: "loro - Lo/Ro Downmix Preferred", value: "loro" },
				],
			},
			{
				type: "select",
				label: "ltrt_cmixlev",
				desc: "Lt/Rt Center Mix Level. The amount of gain the decoder should apply to the center channel when downmixing to stereo in Lt/Rt mode.",
				defaultValue: "0.595",
				options: [
					{ label: "1.414 - Apply +3dB gain", value: "1.414" },
					{ label: "1.189 - Apply +1.5dB gain", value: "1.189" },
					{ label: "1.000 - Apply 0dB gain", value: "1.000" },
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "ltrt_surmixlev",
				desc: "Lt/Rt Surround Mix Level. The amount of gain the decoder should apply to the surround channel(s) when downmixing to stereo in Lt/Rt mode.",
				defaultValue: "0.500",
				options: [
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "loro_cmixlev",
				desc: "Lo/Ro Center Mix Level. The amount of gain the decoder should apply to the center channel when downmixing to stereo in Lo/Ro mode.",
				defaultValue: "0.595",
				options: [
					{ label: "1.414 - Apply +3dB gain", value: "1.414" },
					{ label: "1.189 - Apply +1.5dB gain", value: "1.189" },
					{ label: "1.000 - Apply 0dB gain", value: "1.000" },
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "loro_surmixlev",
				desc: "Lo/Ro Surround Mix Level. The amount of gain the decoder should apply to the surround channel(s) when downmixing to stereo in Lo/Ro mode.",
				defaultValue: "0.500",
				options: [
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "dsurex_mode",
				desc: "Dolby Surround EX Mode - indicates if stream uses Dolby Surround EX (7.1 matrixed to 5.1).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "on - Dolby Surround EX Off", value: "on" },
					{ label: "off - Dolby Surround EX On", value: "off" },
				],
			},
			{
				type: "select",
				label: "dheadphone_mode",
				desc: "Dolby Headphone Mode - indicates if stream uses Dolby Headphone encoding (multi-channel matrixed to 2.0 for use with headphones).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "on - Dolby Headphone Off", value: "on" },
					{ label: "off - Dolby Headphone On", value: "off" },
				],
			},
			{
				type: "select",
				label: "ad_conv_type",
				desc: "A/D Converter Type - indicates if audio passed through HDCD A/D conversion.",
				defaultValue: "standard",
				options: [
					{
						label: "standard - Standard A/D Converter",
						value: "standard",
					},
					{ label: "hdcd - HDCD A/D Converter", value: "hdcd" },
				],
			},
			{
				type: "switch",
				label: "stereo_rematrixing",
				desc: "Stereo Rematrixing - enables mid/side encoding for stereo input to increase quality. Highly recommended to leave enabled.",
				defaultValue: true,
			},
			{
				type: "number",
				label: "cutoff",
				desc: "Set lowpass cutoff frequency in Hz. If 0 (default), encoder selects automatically.",
				defaultValue: 0,
				min: 0,
				max: 24000,
			},
			{
				type: "select",
				label: "channel_coupling",
				desc: "Channel Coupling - combines high frequency information from multiple channels to save bits. (Floating-point only)",
				defaultValue: "auto",
				options: [
					{ label: "auto - Selected by encoder", value: "auto" },
					{ label: "off - Disable channel coupling", value: "off" },
					{ label: "on - Enable channel coupling", value: "on" },
				],
			},
			{
				type: "number",
				label: "cpl_start_band",
				desc: "Coupling Start Band. Use -1 for auto. (Floating-point only)",
				defaultValue: -1,
				min: -1,
				max: 15,
			},
		],
	},
	ac3_fixed: {
		name: "ac3_fixed",
		desc: "AC-3 audio encoder using fixed-point integer math. Suitable for systems without FPU.",
		category: "Lossy General Audio",
		options: [
			{
				type: "switch",
				label: "per_frame_metadata",
				desc: "Allow per-frame metadata changes. If disabled, metadata values set at initialization are used for every frame.",
				defaultValue: false,
			},
			{
				type: "select",
				label: "center_mixlev",
				desc: "Center Mix Level. The amount of gain applied to center channel when downmixing to stereo.",
				defaultValue: "0.595",
				options: [
					{ label: "0.707 - Apply -3dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6dB gain", value: "0.500" },
				],
			},
			{
				type: "select",
				label: "surround_mixlev",
				desc: "Surround Mix Level. The amount of gain applied to surround channel(s) when downmixing to stereo.",
				defaultValue: "0.500",
				options: [
					{ label: "0.707 - Apply -3dB gain", value: "0.707" },
					{ label: "0.500 - Apply -6dB gain", value: "0.500" },
					{ label: "0.000 - Silence surround channel(s)", value: "0.000" },
				],
			},
			{
				type: "number",
				label: "mixing_level",
				desc: "Mixing Level - peak SPL in production environment (80 to 111). Valid values are 80 to 111. Use -1 for unknown. If room_type is not default, this must not be -1.",
				defaultValue: -1,
				min: -1,
				max: 111,
			},
			{
				type: "select",
				label: "room_type",
				desc: "Room Type - describes equalization used during final mixing.",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{
						label: "large - Large Room (dubbing stage with X-curve)",
						value: "large",
					},
					{ label: "small - Small Room (flat equalization)", value: "small" },
				],
			},
			{
				type: "switch",
				label: "copyright",
				desc: "Copyright Indicator - specifies whether a copyright exists for this audio.",
				defaultValue: false,
			},
			{
				type: "number",
				label: "dialnorm",
				desc: "Dialogue Normalization - how far average dialogue level is below 0 dBFS. Default -31 means no volume change.",
				defaultValue: -31,
				min: -31,
				max: -1,
			},
			{
				type: "select",
				label: "dsur_mode",
				desc: "Dolby Surround Mode - indicates if stereo signal uses Dolby Surround (Pro Logic). Does NOT actually apply Dolby Surround processing.",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "off - Not Dolby Surround Encoded", value: "off" },
					{ label: "on - Dolby Surround Encoded", value: "on" },
				],
			},
			{
				type: "switch",
				label: "original",
				desc: "Original Bit Stream Indicator - specifies whether audio is from original source and not a copy.",
				defaultValue: true,
			},
			{
				type: "select",
				label: "dmix_mode",
				desc: "Preferred Stereo Downmix Mode - selects Lt/Rt (Dolby Surround) or Lo/Ro (normal stereo).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "ltrt - Lt/Rt Downmix Preferred", value: "ltrt" },
					{ label: "loro - Lo/Ro Downmix Preferred", value: "loro" },
				],
			},
			{
				type: "select",
				label: "ltrt_cmixlev",
				desc: "Lt/Rt Center Mix Level. The amount of gain the decoder should apply to the center channel when downmixing to stereo in Lt/Rt mode.",
				defaultValue: "0.595",
				options: [
					{ label: "1.414 - Apply +3dB gain", value: "1.414" },
					{ label: "1.189 - Apply +1.5dB gain", value: "1.189" },
					{ label: "1.000 - Apply 0dB gain", value: "1.000" },
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "ltrt_surmixlev",
				desc: "Lt/Rt Surround Mix Level. The amount of gain the decoder should apply to the surround channel(s) when downmixing to stereo in Lt/Rt mode.",
				defaultValue: "0.500",
				options: [
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "loro_cmixlev",
				desc: "Lo/Ro Center Mix Level. The amount of gain the decoder should apply to the center channel when downmixing to stereo in Lo/Ro mode.",
				defaultValue: "0.595",
				options: [
					{ label: "1.414 - Apply +3dB gain", value: "1.414" },
					{ label: "1.189 - Apply +1.5dB gain", value: "1.189" },
					{ label: "1.000 - Apply 0dB gain", value: "1.000" },
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "loro_surmixlev",
				desc: "Lo/Ro Surround Mix Level. The amount of gain the decoder should apply to the surround channel(s) when downmixing to stereo in Lo/Ro mode.",
				defaultValue: "0.500",
				options: [
					{ label: "0.841 - Apply -1.5dB gain", value: "0.841" },
					{ label: "0.707 - Apply -3.0dB gain", value: "0.707" },
					{ label: "0.595 - Apply -4.5dB gain", value: "0.595" },
					{ label: "0.500 - Apply -6.0dB gain", value: "0.500" },
					{ label: "0.000 - Silence Center Channel", value: "0.000" },
				],
			},
			{
				type: "select",
				label: "dsurex_mode",
				desc: "Dolby Surround EX Mode - indicates if stream uses Dolby Surround EX (7.1 matrixed to 5.1).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "on - Dolby Surround EX Off", value: "on" },
					{ label: "off - Dolby Surround EX On", value: "off" },
				],
			},
			{
				type: "select",
				label: "dheadphone_mode",
				desc: "Dolby Headphone Mode - indicates if stream uses Dolby Headphone encoding (multi-channel matrixed to 2.0 for use with headphones).",
				defaultValue: "notindicated",
				options: [
					{
						label: "notindicated - Not Indicated",
						value: "notindicated",
					},
					{ label: "on - Dolby Headphone Off", value: "on" },
					{ label: "off - Dolby Headphone On", value: "off" },
				],
			},
			{
				type: "select",
				label: "ad_conv_type",
				desc: "A/D Converter Type - indicates if audio passed through HDCD A/D conversion.",
				defaultValue: "standard",
				options: [
					{
						label: "standard - Standard A/D Converter",
						value: "standard",
					},
					{ label: "hdcd - HDCD A/D Converter", value: "hdcd" },
				],
			},
			{
				type: "switch",
				label: "stereo_rematrixing",
				desc: "Stereo Rematrixing - enables mid/side encoding for stereo input to increase quality. Highly recommended to leave enabled.",
				defaultValue: true,
			},
			{
				type: "number",
				label: "cutoff",
				desc: "Set lowpass cutoff frequency in Hz. If 0 (default), encoder selects automatically.",
				defaultValue: 0,
				min: 0,
				max: 24000,
			},
		],
	},
	flac: {
		name: "flac",
		desc: "FLAC (Free Lossless Audio Codec) encoder - lossless compression.",
		category: "Lossless Audio",
		options: [
			{
				type: "number",
				label: "compression_level",
				desc: "Compression level. Sets the compression level, which chooses defaults for many other options if they are not set explicitly. Range is between 0 and 12.",
				defaultValue: 5,
				min: 0,
				max: 12,
			},
			{
				type: "number",
				label: "frame_size",
				desc: "Size of frames in samples per channel. Range is between 16 and 65535.",
				defaultValue: 0,
				min: 0,
				max: 65535,
			},
			{
				type: "number",
				label: "lpc_coeff_precision",
				desc: "LPC coefficient precision. Range is between 1 and 15.",
				defaultValue: 15,
				min: 1,
				max: 15,
			},
			{
				type: "select",
				label: "lpc_type",
				desc: "First stage LPC algorithm.",
				defaultValue: "levinson",
				options: ["none", "fixed", "levinson", "cholesky"],
			},
			{
				type: "number",
				label: "lpc_passes",
				desc: "Number of passes for Cholesky factorization during LPC analysis.",
				defaultValue: 2,
				min: 1,
				max: Number.MAX_SAFE_INTEGER,
			},
			{
				type: "number",
				label: "min_partition_order",
				desc: "Minimum partition order.",
				defaultValue: -1,
				min: -1,
				max: 8,
			},
			{
				type: "number",
				label: "max_partition_order",
				desc: "Maximum partition order.",
				defaultValue: -1,
				min: -1,
				max: 8,
			},
			{
				type: "select",
				label: "prediction_order_method",
				desc: "Prediction order method.",
				defaultValue: "estimation",
				options: ["estimation", "2level", "4level", "8level", "search", "log"],
			},
			{
				type: "select",
				label: "ch_mode",
				desc: "Channel mode.",
				defaultValue: "auto",
				options: ["auto", "indep", "left_side", "right_side", "mid_side"],
			},
			{
				type: "switch",
				label: "exact_rice_parameters",
				desc: "If enabled, rice parameters are calculated exactly, slightly improving compression at cost of speed.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "multi_dim_quant",
				desc: "If enabled, a 2nd stage LPC algorithm is applied to fine-tune coefficients, improving compression but slower.",
				defaultValue: false,
			},
		],
	},
	libmp3lame: {
		name: "libmp3lame",
		desc: "LAME MP3 encoder wrapper.",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Set bit rate in bits/s. Setting this automatically activates constant bit rate (CBR) mode.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
			{
				type: "number",
				label: "compression_level",
				desc: "Algorithm quality (0 highest quality/slowest, 9 fastest/worst quality).",
				defaultValue: 5,
				min: 0,
				max: 9,
			},
			{
				type: "number",
				label: "cutoff",
				desc: "Lowpass cutoff frequency in Hz. If 0, encoder adjusts dynamically.",
				defaultValue: 0,
				min: 0,
				max: 999999,
			},
			{
				type: "switch",
				label: "reservoir",
				desc: "Enable bit reservoir.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "joint_stereo",
				desc: "Allow joint stereo (mid/side) on a frame-by-frame basis.",
				defaultValue: true,
			},
			{
				type: "switch",
				label: "abr",
				desc: "Enable ABR mode.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "copyright",
				desc: "Set MPEG audio copyright flag.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "original",
				desc: "Set MPEG audio original flag.",
				defaultValue: true,
			},
		],
	},
	libopencore_amrnb: {
		name: "libopencore_amrnb",
		desc: "OpenCORE Adaptive Multi-Rate Narrowband encoder (mono only, typically 8000 Hz).",
		category: "Speech & Voice Codecs",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Bit rate in bits/s. Rounds to nearest valid value if not exact.",
				defaultValue: "12200",
				options: [
					"4750",
					"5150",
					"5900",
					"6700",
					"7400",
					"7950",
					"10200",
					"12200",
				],
			},
			{
				type: "switch",
				label: "dtx",
				desc: "Allow discontinuous transmission (generate comfort noise).",
				defaultValue: false,
			},
		],
	},
	libopus: {
		name: "libopus",
		desc: "libopus Opus Interactive Audio Codec encoder wrapper.",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Set bit rate in bits/s.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
			{
				type: "select",
				label: "vbr",
				desc: "VBR mode.",
				defaultValue: "on",
				options: [
					{ label: "off - constant bit rate (hard-cbr)", value: "off" },
					{ label: "on - variable bit rate", value: "on" },
					{
						label: "constrained - constrained VBR (cvbr)",
						value: "constrained",
					},
				],
			},
			{
				type: "number",
				label: "compression_level",
				desc: "Encoding algorithm complexity. Range is between 0 and 10. 0 gives the fastest encodes but lower quality, while 10 gives the highest quality but slowest encoding. ",
				defaultValue: 10,
				min: 0,
				max: 10,
			},
			{
				type: "select",
				label: "frame_duration",
				desc: "Maximum frame size in milliseconds. Smaller frames = lower latency but less quality at given bitrate.",
				defaultValue: "20",
				options: ["2.5", "5", "10", "20", "40", "60"],
			},
			{
				type: "number",
				label: "packet_loss",
				desc: "Expected packet loss percentage. Range is between 0 and 100.",
				defaultValue: 0,
				min: 0,
				max: 100,
			},
			{
				type: "switch",
				label: "fec",
				desc: "Enable inband forward error correction. Requires packet_loss > 0.",
				defaultValue: false,
			},
			{
				type: "select",
				label: "application",
				desc: "Intended application type.",
				defaultValue: "audio",
				options: [
					{ label: "voip - favor speech intelligibility", value: "voip" },
					{
						label: "audio - favor faithfulness to input",
						value: "audio",
					},
					{
						label: "lowdelay - restrict to lowest delay modes",
						value: "lowdelay",
					},
				],
			},
			{
				type: "select",
				label: "cutoff",
				desc: "Cutoff bandwidth in Hz. 0 disables cutoff.",
				defaultValue: "0",
				options: ["0", "4000", "6000", "8000", "12000", "20000"],
			},
			{
				type: "select",
				label: "mapping_family",
				desc: "Set channel mapping family to be used by the encoder. The default value of -1 uses mapping family 0 for mono and stereo inputs, and mapping family 1 otherwise. The default also disables the surround masking and LFE bandwidth optimizations in libopus, and requires that the input contains 8 channels or fewer.",
				defaultValue: "-1",
				options: [
					{ label: "-1 - auto", value: "-1" },
					{ label: "0 - mono/stereo", value: "0" },
					{
						label: "1 - surround with masking and LFE optimizations",
						value: "1",
					},
					{
						label: "255 - independent streams, unspecified layout",
						value: "255",
					},
				],
			},
			{
				type: "switch",
				label: "dtx",
				desc: "Allow discontinuous transmission.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "apply_phase_inv",
				desc: "Disable phase inversion for intensity stereo (improves mono downmix, slightly reduces stereo quality).",
				defaultValue: true,
			},
		],
	},
	libshine: {
		name: "libshine",
		desc: "Shine fixed-point MP3 encoder (CBR only, lower quality than LAME but faster on FPU-less systems).",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Set bit rate in bits/s.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
		],
	},
	libtwolame: {
		name: "libtwolame",
		desc: "TwoLAME MP2 encoder wrapper.",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Set bit rate in bits/s.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
			{
				type: "number",
				label: "q",
				desc: "Quality for experimental VBR support. Range is between -50 and 50. Higher = better quality.",
				defaultValue: 0,
				min: -50,
				max: 50,
			},
			{
				type: "select",
				label: "mode",
				desc: "Audio mode.",
				defaultValue: "auto",
				options: ["auto", "stereo", "joint_stereo", "dual_channel", "mono"],
			},
			{
				type: "number",
				label: "psymodel",
				desc: "Psychoacoustic model. Range is between -1 and 4.",
				defaultValue: 3,
				min: -1,
				max: 4,
			},
			{
				type: "switch",
				label: "energy_levels",
				desc: "Enable energy levels extensions.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "error_protection",
				desc: "Enable CRC error protection.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "copyright",
				desc: "Set MPEG audio copyright flag.",
				defaultValue: false,
			},
			{
				type: "switch",
				label: "original",
				desc: "Set MPEG audio original flag.",
				defaultValue: false,
			},
		],
	},
	libvo_amrwbenc: {
		name: "libvo_amrwbenc",
		desc: "VisualOn Adaptive Multi-Rate Wideband encoder (mono only, typically 16000 Hz).",
		category: "Speech & Voice Codecs",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Bit rate in bits/s.",
				defaultValue: "14250",
				options: [
					"6600",
					"8850",
					"12650",
					"14250",
					"15850",
					"18250",
					"19850",
					"23050",
					"23850",
				],
			},
			{
				type: "switch",
				label: "dtx",
				desc: "Allow discontinuous transmission (generate comfort noise).",
				defaultValue: false,
			},
		],
	},
	libvorbis: {
		name: "libvorbis",
		desc: "libvorbis encoder wrapper. Requires `--enable-libvorbis`.",
		category: "Lossy General Audio",
		options: [
			{
				type: "select",
				label: "b",
				desc: "Bit rate in bits/s for ABR.",
				defaultValue: "128k",
				options: [
					"320k",
					"256k",
					"224k",
					"192k",
					"160k",
					"128k",
					"112k",
					"96k",
					"80k",
					"64k",
					"48k",
					"40k",
					"32k",
					"24k",
					"16k",
					"8k",
				],
			},
			{
				type: "number",
				label: "cutoff",
				desc: "Cutoff bandwidth in Hz. 0 disables cutoff.",
				defaultValue: 0,
				min: 0,
				max: 2147483647,
			},
			{
				type: "number",
				label: "minrate",
				desc: "Minimum bit rate in bits/s.",
				defaultValue: 0,
				min: -2147483647,
				max: 2147483647,
			},
			{
				type: "number",
				label: "maxrate",
				desc: "Maximum bit rate in bits/s (only effective in ABR mode).",
				defaultValue: -1,
				min: -1,
				max: 2147483647,
			},
			{
				type: "number",
				label: "iblock",
				desc: "Noise floor bias for impulse blocks. Range is between -15.0 and 0.0. Negative values improve transient response at cost of higher bitrate.",
				defaultValue: 0,
				min: -15.0,
				max: 0.0,
			},
		],
	},
	wavpack: {
		name: "wavpack",
		desc: "WavPack lossless audio encoder.",
		category: "Lossless Audio",
		options: [
			{
				type: "number",
				label: "frame_size",
				desc: "Block size in samples. Default automatically decided based on sample rate and channels.",
				defaultValue: 0,
				min: 128,
				max: 131072,
			},
			{
				type: "select",
				label: "compression_level",
				desc: "Compression level.",
				defaultValue: "h",
				options: [
					{ label: "f - fast (low compression)", value: "f" },
					{ label: "h - high", value: "h" },
					{ label: "hh - very high", value: "hh" },
					{ label: "x - extra", value: "x" },
				],
			},
			{
				type: "select",
				label: "joint_stereo",
				desc: "Joint stereo mode.",
				defaultValue: "auto",
				options: [
					{ label: "auto - let encoder decide", value: "auto" },
					{ label: "on - force mid/side encoding", value: "on" },
					{ label: "off - force left/right encoding", value: "off" },
				],
			},
			{
				type: "switch",
				label: "optimize_mono",
				desc: "Enable optimization for mono (only effective for non-mono streams).",
				defaultValue: false,
			},
		],
	},
} satisfies Partial<AUDIO_ENCODERS>;

export const ENCODER_GROUPS = [
	{
		category: "Lossy General Audio",
		encoders: [
			"aac",
			"ac3",
			"ac3_fixed",
			"libtwolame",
			"libmp3lame",
			"libshine",
			"libopus",
			"libvorbis",
		],
	},
	{
		category: "Lossless Audio",
		encoders: ["flac", "wavpack"],
	},
	{
		category: "Speech & Voice Codecs",
		encoders: ["libopencore_amrnb", "libvo_amrwbenc"],
	},
];

export const EXTENSIONS_LIST = [
	".aac",
	".ac3",
	".ac4",
	".adx",
	".aiff",
	".al",
	".alp",
	".amr",
	".apm",
	".aptx",
	".asf",
	".ast",
	".au",
	".bit",
	".c2",
	".caf",
	".cvg",
	".daud",
	".dfpwm",
	".dts",
	".eac3",
	".flac",
	".g722",
	".g723",
	".g726",
	".gsm",
	".ilbc",
	".mlp",
	".mmf",
	".mp2",
	".mp3",
	".oma",
	".opus",
	".pcm",
	".rso",
	".sbc",
	".sf",
	".sox",
	".spdif",
	".spx",
	".thd",
	".tta",
	".ul",
	".vag",
	".vidc",
	".voc",
	".w64",
	".wav",
	".wsa",
	".wv",
] satisfies EXTENSIONS;

export const MUXER_TO_EXTENSION = {
	alaw: ".al",
	daud: ".daud",
	dfpwm: ".dfpwm",
	f32be: ".pcm",
	f32le: ".pcm",
	f64be: ".pcm",
	f64le: ".pcm",
	mulaw: ".ul",
	s16be: ".pcm",
	s16le: ".pcm",
	s24be: ".pcm",
	s24le: ".pcm",
	s32be: ".pcm",
	s32le: ".pcm",
	s8: ".pcm",
	u16be: ".pcm",
	u16le: ".pcm",
	u24be: ".pcm",
	u24le: ".pcm",
	u32be: ".pcm",
	u32le: ".pcm",
	u8: ".pcm",
	vidc: ".vidc",
	ac3: ".ac3",
	ac4: ".ac4",
	adts: ".aac",
	adx: ".adx",
	aiff: ".aiff",
	alp: ".alp",
	amr: ".amr",
	apm: ".apm",
	aptx: ".aptx",
	aptx_hd: ".aptx",
	argo_asf: ".asf",
	argo_cvg: ".cvg",
	ast: ".ast",
	au: ".au",
	bit: ".bit",
	caf: ".caf",
	codec2: ".c2",
	codec2raw: ".c2",
	dts: ".dts",
	eac3: ".eac3",
	flac: ".flac",
	g722: ".g722",
	g723_1: ".g723",
	g726: ".g726",
	g726le: ".g726",
	gsm: ".gsm",
	ilbc: ".ilbc",
	ircam: ".sf",
	kvag: ".vag",
	latm: ".aac",
	mlp: ".mlp",
	mmf: ".mmf",
	mp2: ".mp2",
	mp3: ".mp3",
	oma: ".oma",
	opus: ".opus",
	rso: ".rso",
	sbc: ".sbc",
	sox: ".sox",
	spdif: ".spdif",
	spx: ".spx",
	tta: ".tta",
	truehd: ".thd",
	voc: ".voc",
	w64: ".w64",
	wav: ".wav",
	wsaud: ".wsa",
	wv: ".wv",
	alsa: "",
	oss: "",
	pulse: "",
	oga: ".oga",
} satisfies AUDIO_MUXER_EXTENSIONS;
