export type FILTERS = [
	"abench",
	"acompressor",
	"acontrast",
	"acopy",
	"acue",
	"acrossfade",
	"acrusher",
	"adeclick",
	"adeclip",
	"adecorrelate",
	"adelay",
	"adenorm",
	"aderivative",
	"adrc",
	"adynamicequalizer",
	"adynamicsmooth",
	"aecho",
	"aemphasis",
	"aeval",
	"aexciter",
	"afade",
	"afftdn",
	"afftfilt",
	"aformat",
	"afreqshift",
	"afwtdn",
	"agate",
	"aintegral",
	"alatency",
	"alimiter",
	"allpass",
	"aloop",
	"ametadata",
	"amultiply",
	"anlmdn",
	"anlmf",
	"anlms",
	"anull",
	"apad",
	"aperms",
	"aphaser",
	"aphaseshift",
	"apsnr",
	"apsyclip",
	"apulsator",
	"arealtime",
	"aresample",
	"areverse",
	"arls",
	"arnndn",
	"asdr",
	"asendcmd",
	"asetnsamples",
	"asetpts",
	"asetrate",
	"asettb",
	"ashowinfo",
	"asidedata",
	"asisdr",
	"asoftclip",
	"aspectralstats",
	"asr",
	"astats",
	"asubboost",
	"asubcut",
	"asupercut",
	"asuperpass",
	"asuperstop",
	"atempo",
	"atilt",
	"atrim",
	"axcorrelate",
	"azmq",
	"bandpass",
	"bandreject",
	"bass",
	"biquad",
	"bs2b",
	"channelmap",
	"chorus",
	"compand",
	"compensationdelay",
	"crossfeed",
	"crystalizer",
	"dcshift",
	"deesser",
	"dialoguenhance",
	"drmeter",
	"dynaudnorm",
	"earwax",
	"equalizer",
	"extrastereo",
	"firequalizer",
	"flanger",
	"haas",
	"hdcd",
	"highpass",
	"highshelf",
	"loudnorm",
	"lowpass",
	"lowshelf",
	"mcompand",
	"pan",
	"replaygain",
	"rubberband",
	"sidechaincompress",
	"sidechaingate",
	"silencedetect",
	"silenceremove",
	"sofalizer",
	"speechnorm",
	"stereotools",
	"stereowiden",
	"superequalizer",
	"surround",
	"tiltshelf",
	"treble",
	"tremolo",
	"vibrato",
	"virtualbass",
	"volume",
	"volumedetect",
	"afifo",
];

type AUDIO_FILTERS = FILTERS[number];
type AUDIO_FILTER_OPTION<T extends AUDIO_FILTERS> = {
	name: T;
	desc: string;
};

export type AUDIO_FILTERS_OPTIONS = AUDIO_FILTER_OPTION<AUDIO_FILTERS>[];

export type SettingsForm = {
	audio: {
		audioCodec: string;
		audioQuality: string;
		audioFilter: string;
	};
	global: {
		outputDirectoryPath: string;
		concurrency: number;
		overwrite: boolean;
		noOverwrite: boolean;
		statsPeriod: number;
	};
};
